server:
  port: ${SERVER_PORT:8183}

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/post}
    username: ${USER_DB:user}
    password: ${PASSWORD_DB:password}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:database_ms_post_changelog.xml
    driver-class-name: org.postgresql.Driver
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration